### ISSUE TITLE
[BUG] PHP 8.1 not fully supported

### ISSUE THREAD

**Issue by josefglatz** [eliashaeussler/typo3-warming#125]
### TYPO3 version

11.5

### PHP version

8.1

### Extension version

0.4.5

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

linux

### Current behavior

CacheWarmupController throws a undefined array key warning for the fetchSitesAction

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@josefglatz Thanks for the issue and the quick fix! This is now released as `0.4.6`.
