### ISSUE TITLE
[BUG] Sitemaps cannot be located

### ISSUE THREAD

**Issue by randomresult** [eliashaeussler/typo3-warming#137]
### TYPO3 version

11.5.16

### PHP version

8.1.1

### Extension version

0.4.6

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

macOs 11.6

### Current behavior

We have installed the extension using composer. then we added a sitemap.xml in the sites configuration. 
When trying to execute the warmup using the toolbar, it says that no sitemap is found (we checked the frontend path and the sitemap exist) 
When we checked, no tx_warming.php was found in var/cache/code/core
When we then logout and login again, the file appears in var/cache/code/core but still the toolbar tells us, that no siteamap is found. 

### Steps to reproduce

To make the tx_warming.php file appear in var/cache/code/core we need to logout from the backend and login again.

### Additional context

We are running a Multilanguage config with english as default and de as second Language. 
tx_warming.php contains the following informations once generated:

```php
<?php
return array (
  'sitemaps' => 
  array (
    'datron' => 
    array (
      'default' => 'https://ourinstall.localhost/sitemap.xml',
      1 => 'https://ourinstall.localhost/de/sitemap.xml',
    ),
  ),
);
```

Additional to our sitepackage, we install the following composer-components:

```
    "b13/assetcollector": "1.6.0",
    "b13/container": "1.6.1",
    "b13/picture": "1.2.3",
    "cweagans/composer-patches": "1.7.2",
    "derhansen/form_crshield": "^1.2",
    "georgringer/eventnews": "5.0.1",
    "georgringer/news": "9.4.0",
    "helhum/dotenv-connector": "v3.0.1",
    "helhum/typo3-console": "v7.1.2",
    "ichhabrecht/content-defender": "3.2.3",
    "internetgalerie/ig-slug": "v1.0.6",
    "lavitto/typo3-form-to-database": "^2.1",
    "lochmueller/staticfilecache": "12.5.0",
    "plan2net/webp": "4.1.2",
    "sjbr/static-info-tables": "v11.5.2",
    "t3monitor/t3monitoring_client": "dev-master#e1be692e86e9478109123741e731b762d1a63461",
    "tritum/form-element-linked-checkbox": "3.0.0",
    "typo3/cms-adminpanel": "*",
    "typo3/cms-backend": "*",
    "typo3/cms-belog": "*",
    "typo3/cms-beuser": "*",
    "typo3/cms-core": "v11.5.16",
    "typo3/cms-extbase": "*",
    "typo3/cms-extensionmanager": "*",
    "typo3/cms-filelist": "*",
    "typo3/cms-filemetadata": "*",
    "typo3/cms-fluid": "*",
    "typo3/cms-fluid-styled-content": "*",
    "typo3/cms-form": "*",
    "typo3/cms-frontend": "*",
    "typo3/cms-impexp": "*",
    "typo3/cms-info": "*",
    "typo3/cms-install": "*",
    "typo3/cms-linkvalidator": "*",
    "typo3/cms-lowlevel": "*",
    "typo3/cms-opendocs": "*",
    "typo3/cms-recordlist": "*",
    "typo3/cms-recycler": "*",
    "typo3/cms-redirects": "*",
    "typo3/cms-reports": "*",
    "typo3/cms-rte-ckeditor": "*",
    "typo3/cms-scheduler": "*",
    "typo3/cms-seo": "*",
    "typo3/cms-setup": "*",
    "typo3/cms-t3editor": "*",
    "typo3/cms-tstemplate": "*",
    "typo3/cms-viewpage": "*",
    "webcoast/deferred-image-processing": "v1.1.0",
    "eliashaeussler/typo3-warming": "^0.4.6",
    "lochmueller/language-detection": "^3.0",
     "typo3/cms-indexed-search": "^11.5.16"
```

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/4463384/197481915-5b83912d-8804-4b09-95b6-22728907f059.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/4463384/197481917-a4609264-1479-4260-a1f6-e85bddfc5deb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @randomresult, please check the following requirements:

* Are all languages enabled in your site config?
* Does the appropriate BE user have access to these languages (in case it's not an admin user)?
* Is your base url properly configured (it must contain a hostname, only `/` is not enough)?
* Are your sitemaps accessible (no auth or similar required)?

**Comment by eliashaeussler** [comment]
@randomresult @Alagts From what I can see, it seems like the request factory is unable to perform a `HEAD` request on your `sitemap.xml`. Can you by chance try step-debugging and check whether the response in the following line is successful?

https://github.com/eliashaeussler/typo3-warming/blob/ce710d25bda627a254d175b3dc9ae690eb4d9f48/Classes/Sitemap/SitemapLocator.php#L124

**Comment by eliashaeussler** [comment]
And one more thing:

Do you probably have some additional configuration for the request factory in place? Something like written here: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/RestRequests/Index.html

**Comment by eliashaeussler** [comment]
Hi @randomresult @Alagts, is your problem solved in the meantime?

**Comment by eliashaeussler** [comment]
I'm closing this issue due to lack of feedback. If the issue still persists, feel free to open a new issue.
