### ISSUE TITLE
[BUG] TYPO3 pagetree context menu when sysfolder should be hidden

### ISSUE THREAD

**Issue by josefglatz** [eliashaeussler/typo3-warming#161]
### TYPO3 version

11.5

### PHP version

8.1

### Extension version

latest stable

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

nix

### Current behavior

![image](https://user-images.githubusercontent.com/2861556/205000848-d1bb2185-6c23-49ff-bed5-3553884cd059.png)

### Expected behavior

The context menu item for "warming" could be hidden when page is type `PageRepository::DOKTYPE_SYSFOLDER`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @josefglatz, thanks for your issue! This is now resolved and released with version `0.4.7`.
