### ISSUE TITLE
[BUG] sitemap not found in XMLParser.php

### ISSUE THREAD

**Issue by IngoMueller** [eliashaeussler/typo3-warming#182]
### TYPO3 version

10.4.34

### PHP version

7.4.32

### Extension version

0.4.8

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Linux 5.15.49

### Current behavior

Hey Elias,

my Rootpage is a Shortcut to a Page in the Pagetree.
If i configure the slug in the siteconfig like this xml_sitemap_path: startseite/sitemap.xml cache warmup works fine for me.
But when i configure it without the slug, the extension dont respect the redirect and can't find the sitemap.xml.

Thanks for your help

Ingo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @IngoMueller, thanks for your issue. This is now resolved upstream with eliashaeussler/cache-warmup#162 and released as `0.8.3`.
