### ISSUE TITLE
[FEATURE] Warm up multiple sites/pages with one request

### ISSUE THREAD

**Issue by criwe** [eliashaeussler/typo3-warming#198]
### Is your feature request related to a problem?

In bigger multidomain installation, it´s frustrating to warm up all sites one by one.

### Describe the solution you'd like

Add option to warm up caches of all sitemaps/pages at once in multidomain installation

Best regards
Christoph

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @criwe, this will be part of the next major release (which will support TYPO3 v12 only). I'll keep you updated.

**Comment by criwe** [comment]
@eliashaeussler thank you, I am curious about it :-)

**Comment by eliashaeussler** [comment]
Hey @criwe, I already merged the core features of the upcoming TYPO3 v12 compatibility release into the `main` branch. If you want, you can already test it out and give feedback. :)

**Comment by eliashaeussler** [comment]
This feature is part of the [`1.0.0`](https://github.com/eliashaeussler/typo3-warming/releases/tag/1.0.0) release. Have fun with it!

**Comment by criwe** [comment]
@eliashaeussler sorry for the late reply, I´ve testet the great new feature, works perfect. Thanks a lot!
