### ISSUE TITLE
[FEATURE] max parallel processes + multi sitemap

### ISSUE THREAD

**Issue by in-session** [eliashaeussler/typo3-warming#199]
### Is your feature request related to a problem?

1. Warming many pages
2. Multiple sitemaps from the robots 

### Describe the solution you'd like

1. For example, a website with 5,000 pages, it should be possible to set the parallel processes of warming up or to fix a maximum number of requests per second.  
2. It would be desirable that, for example, all sitemaps can be taken from the robots. Or the function to manually include one or more sitemaps.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @in-session, thanks for your feature requests.

> For example, a website with 5,000 pages, it should be possible to set the parallel processes of warming up or to fix a maximum number of requests per second.

This is already possible with crawler options. Have a look at [`crawlerOptions`](https://docs.typo3.org/p/eliashaeussler/typo3-warming/main/en-us/Configuration/ExtensionConfiguration.html#confval-crawlerOptions) (for requests from TYPO3 backend) and [`verboseCrawlerOptions`](https://docs.typo3.org/p/eliashaeussler/typo3-warming/main/en-us/Configuration/ExtensionConfiguration.html#confval-verboseCrawlerOptions) (for requests from CLI). The available crawler options are configured [here](https://github.com/eliashaeussler/cache-warmup#crawler-configuration). Note that crawler options must be configured as JSON-encoded string, e.g. `{"concurrency": 3}`.

> It would be desirable that, for example, all sitemaps can be taken from the robots. Or the function to manually include one or more sitemaps.

This will be part of the next major release (which will support TYPO3 v12 only). I'll keep you updated.

**Comment by eliashaeussler** [comment]
> It would be desirable that, for example, all sitemaps can be taken from the robots. Or the function to manually include one or more sitemaps.

This feature is part of the [`1.0.0`](https://github.com/eliashaeussler/typo3-warming/releases/tag/1.0.0) release. Have fun with it!
