### ISSUE TITLE
[BUG] Argument 1 passed to GuzzleHttp\Psr7\Uri::__construct() must be of the type string, object given

### ISSUE THREAD

**Issue by mkempe** [eliashaeussler/typo3-warming#239]
### TYPO3 version

11.5.26

### PHP version

7.4.33

### Extension version

0.5.1

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Linux

### Current behavior

When i run the following command `typo3cms warming:cachewarmup --pages 1` an exception (`Argument 1 passed to GuzzleHttp\Psr7\Uri::__construct() must be of the type string, object given`) is thrown. 

### Expected behavior

The sitemap(s) should be parsed without exception.

### Additional context

Hallo,

first of all, many thanks for this great extension.

I have already tried to fix the error, but I don't know if this would be the right approach. The error is in the `cache-warmup` package, in the 0.8 release, in CacheWarmupCommand.php, line 230: https://github.com/eliashaeussler/cache-warmup/blob/9a01813efbb9c62a2d6a54da75399557a22d0afd/src/Command/CacheWarmupCommand.php#L230

It is expected that the passed Url is a string, but it is a `TYPO3\CMS\Core\Http\Uri` object. A possible fix would be to explizit cast the Url to string. Would that be the correct procedure?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @mkempe, thanks for this issue. It's now resolved as part of the `0.5.2` release.

**Comment by mkempe** [comment]
Hi @eliashaeussler, many thank for the fix, works like charm.

Thanks again for the great extension and your time.
