### ISSUE TITLE
[FEATURE] Transform README to TYPO3 documentation layout

### ISSUE THREAD

**Issue by eliashaeussler** [eliashaeussler/typo3-warming#27]
### Is your feature request related to a problem?

This TYPO3 extension currently does not provide an official documentation on the TYPO3 documentation server. Instead, "only" a `README.md` is available.

### Describe the solution you'd like

The existing `README.md` should be transformed to the default TYPO3 documentation layout.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by linawolf** [comment]
Draft is rendered, Please check it here: https://docs.typo3.org/p/eliashaeussler/typo3-warming/draft/en-us/

**Comment by eliashaeussler** [comment]
@linawolf Nice, thanks for approving! 🙂
