### ISSUE TITLE
[BUG] Links not fetched when using sub path

### ISSUE THREAD

**Issue by maikschneider** [eliashaeussler/typo3-warming#398]
### PHP version

8.1

### Package version

0.5.2

### Application

Composer

### Operating system

RHEL9

### Current behavior

In TYPO3 v11 `typo3cms warming:cachewarmup --sites=1 -v` fails to warmup the sitemap entries, however `cache-warmup -p "https://domain.de/sub/sitemap.xml"` is working.

Using the warming command, the sitemap is fetched correctly, the individual links are shown with progress bar and dealt with one after another - but every request fails. The requests are not even reaching the web server - the access.log has no entries for these links. I guess it has something to do with the sub path in the `base` path of my TYPO3 installation `https://domain.de/sub`.

Unfortunately the logging/log-level feature is only available for v12. Do you have an idea what is going on or idea where to insert a manual debug?

Cheers

**Comment by maikschneider** [comment]
Hey @eliashaeussler,

thanks for the fast feedback! Oha, I didn't thought about this - yes, the application is behind a proxy, the HTTP configuration has a proxy setting.

Is it possible to add these HTTP settings as `client_options` in `crawlerOptions`?

**Comment by eliashaeussler** [comment]
@maikschneider Yes, you can use the `client_config` crawler option. This config is then merged with `$GLOBALS['TYPO3_CONF_VARS']['HTTP']` using `ArrayUtility::mergeRecursiveWithOverrule()` (see https://github.com/eliashaeussler/typo3-warming/blob/0.5.3/Classes/Crawler/ConfigurableClientTrait.php#L50).

Keep in mind that this must be configured for both `crawlerOptions` (Backend context) and `verboseCrawlerOptions` (CLI context) if you face problems in both contexts.
