### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DanielZeilfelder** [eliashaeussler/typo3-warming#484]
### TYPO3 version

12.4.7

### PHP version

8.2.8

### Extension version

1.1.2

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

macOS 14.0

### Current behavior

Warming icon does not show in backend but works!

### Expected behavior

Icon beside "clear cache"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @DanielZeilfelder, thanks for your issue. This is now fixed and released as `1.1.3`.
