### ISSUE TITLE
[BUG] Support the dark mode of TYPO3's backend top icon toolbar

### ISSUE THREAD

**Issue by josefglatz** [eliashaeussler/typo3-warming#511]
### TYPO3 version

e.g. 12

### PHP version

-

### Extension version

-

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

-

### Current behavior

<img width="398" alt="image" src="https://github.com/eliashaeussler/typo3-warming/assets/2861556/3cfc7f18-04d0-4f7b-93e6-d8ab2655f57d">

currently the icon is shown if you take a closer look.

### Expected behavior

Since TYPO3 supports partially support for dark mode of e.g. OS oder browser settings the icon should also switch to "bright".

I think this can be achieved simply by using correct svg markup as the icon is pretty simple.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @josefglatz, this was already reported with #484 and #495 and resolved with #496. Which version of EXT:warming are you using? It should be solved since `1.1.3`.

**Comment by eliashaeussler** [comment]
I'm closing this issue for the moment. Feel free to comment if it's still persistent.
