### ISSUE TITLE
[FEATURE]Make Basic Auth Configuration possible

### ISSUE THREAD

**Issue by ChristianOsswald** [eliashaeussler/typo3-warming#522]
### Is your feature request related to a problem?

I got a basic auth protection for my preview instances. CLI command "typo3 warming:cachewarmup" is failing there.

### Describe the solution you'd like

A possibility to configure basic auth credentials. I would prefer as cli options.

### Additional context

TYPO3 12.4.8
typo3-warming 2.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by ChristianOsswald** [comment]
Could be solved by setting base URL in config.yaml
base: https://user:password@domain.com/

**Comment by ChristianOsswald** [comment]
I use .env file and helhum/dotenv-connector for this. So I can differentiate between stages.

It looks like this in config.yaml 
base: 'https://%env(BASE_DOMAIN)%/'

and like this in .env
BASE_DOMAIN='https://user:password@domain.com'

**Comment by ChristianOsswald** [comment]
I was not able to reproduce the behavior. Maybe this feature would be nice.

**Comment by eliashaeussler** [comment]
Hi @ChristianOsswald, sorry for the late response. This is already possible, see #85 for more information.
