### ISSUE TITLE
[BUG] Environment variable TYPO3_CONTEXT not always considered

### ISSUE THREAD

**Issue by brotkrueml** [eliashaeussler/typo3-warming#535]
### TYPO3 version

12.4.9

### PHP version

8.2.13

### Extension version

2.0.0

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Debian 11/12

### Current behavior

Using the following command to warmup a page ID for all languages works correctly, the URL configured in sites/.../config.yaml is correctly fetched:

    TYPO3_CONTEXT=Production vendor/bin/typo3 warming:cachewarmup -v -p 1

Output:

    https://www.example.com/en/
    https://www.example.com/de/

However, when calling the sitemap for a language the current URL is used:

    TYPO3_CONTEXT=Production vendor/bin/typo3 warming:cachewarmup -v -s my_website -l 1

Output:

    https://example.ddev.site/de/sitemap.xml
    ...

This problem occurs especially when deploying on a server where the context is important to warm up the relevant pages of a specific context (like Production and Production/Testing).

Additionally, it seems that sub-contexts have no effect, so when setting the context to `Production/Testing` the `Production` site is used for page warmup:

     TYPO3_CONTEXT=Production/Testing vendor/bin/typo3 warming:cachewarmup -v -p 1
     
Output:

    https://www.example.com/en/
    https://www.example.com/de/

### Expected behavior

The application context is considered correctly.

### Steps to reproduce

1. Have a site config with base variants.
2. Call on a ddev box the warmup command with another application context (like described above, for example `Production`) for a sitemap. 
3. Call on a ddev box the warmup command with another application context (like described above, for example `Production/Testing`) for a sitemap. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @brotkrueml, thanks for the detailed bug report. Can you please update EXT:sitemap_locator to 0.1.2 and check if the issue is solved by eliashaeussler/typo3-sitemap-locator#18?

**Comment by brotkrueml** [comment]
Thanks for the quick reply. I can test it next week.

**Comment by brotkrueml** [comment]
@eliashaeussler Yes, it works now. Thank you for the fix :+1:
