### ISSUE TITLE
[FEATURE] Provide support for PHP 8.3 with TYPO3 11LTS

### ISSUE THREAD

**Issue by oliverklee** [eliashaeussler/typo3-warming#695]
### Is your feature request related to a problem?

For a site that still is on TYPO3 11LTS (and still needs to be due to migration issues) and that already is on PHP 8.3, I'd like to be able to use this extension.

### Describe the solution you'd like

A 0.5.x release that is installable and works with PHP 8.3.

### Additional context

I can create a PR to backport the [corresponding commit](https://github.com/eliashaeussler/typo3-warming/commit/0965421982bc4b232c7cb0f792521c6079be2855) to the [`0.5.x branch`](https://github.com/eliashaeussler/typo3-warming/tree/0.5.x) if you're open to releasing another 0.5.x version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @oliverklee, I normally don't backport features to the 0.5.x release branch. But if you're willing to backport it, I'll for sure merge and release it :)

**Comment by eliashaeussler** [comment]
Thanks @oliverklee, PR merged and released as `0.5.5` :) Happy warming! 🚀

**Comment by oliverklee** [comment]
Thank you, @eliashaeussler, for getting this PR to green and for releasing a new version. I really appreciate that! :heart:
