### ISSUE TITLE
[FEATURE] ContentExceptionHandler Error Reporting

### ISSUE THREAD

**Issue by josefglatz** [eliashaeussler/typo3-warming#704]
### Is your feature request related to a problem?

Is it possible to add a feature to report also if a page returns an okish 2xx response but warns that any CE throws errors with "Opps an error occured..." string?

### Describe the solution you'd like

Feature to enable a check for that string. The page will then be marked as not ok

### Describe alternatives you've considered

Screaming Frog spider and searching for that string

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @josefglatz, thanks for your feature request!

With the new event system of `eliashaeussler/cache-warmup` (and especially the events provided with https://github.com/eliashaeussler/cache-warmup/pull/403), this will be possible in EXT:warming. However, I first need to migrate the extension towards v3 of the `cache-warmup` library. I'll keep you updated on the progress here.

**Comment by josefglatz** [comment]
Wow, thank you so much Elias! That makes the extension more powerful!!!

**Comment by eliashaeussler** [comment]
This feature won't be part of the extension itself, but with the new event system it can be easily achieved in a custom extension with a custom event listener. See the following example:

```php
use EliasHaeussler\CacheWarmup;
use Psr\Http\Message;

final class BlacklistedWordsEventListener
{
    private const BLACKLIST = [
        'Oops, an error occurred!',
        'has no rendering definition!',
    ];

    public function __invoke(CacheWarmup\Event\UrlCrawlingSucceeded $event): void
    {
        if ($this->responseHasBlacklistedWord($event->response())) {
            $event->setResult(
                CacheWarmup\Result\CrawlingResult::createFailed(
                    $event->uri(),
                    ['reason' => 'Blacklisted words found'],
                ),
            );
        }
    }

    private function responseHasBlacklistedWord(Message\ResponseInterface $response): bool
    {
        $body = $response->getBody();
        $contents = (string)$body;
        $body->rewind();

        return str_ireplace(self::BLACKLIST, '', $contents) !== $contents;
    }
}
```
