### ISSUE TITLE
[FEATURE] multisite support

### ISSUE THREAD

**Issue by Make66** [eliashaeussler/typo3-warming#717]
### Is your feature request related to a problem?

we have 50 small sites in 1 T3. Warming them all up is a bit complicated and needs a script that needs to be changed, whenever we add/remove a site.

### Describe the solution you'd like

Command could have an option like "--all" to address all sites for warming

### Describe alternatives you've considered

Create and maintain a bash script

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @Make66, thanks for your feature request! This is now implemented with #720 and released as `3.1.0`. Just use the special keyword `all` for the `-s|--sites` command option:

```bash
typo3 warming:cachewarmup -s all
```

Have fun!
