### ISSUE TITLE
[BUG] PHP 8.1 compatibility

### ISSUE THREAD

**Issue by IngoMueller** [eliashaeussler/typo3-warming#73]
### TYPO3 version

11.5.12

### PHP version

8.1.9

### Extension version

0.3.19

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Apache/2.4.54 (Debian)

### Current behavior

Hey Elias,

An Error is thrown in TYPO3 - Log after running Cache-Warmup:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "languageId" in ....typo3conf/ext/warming/Classes/Controller/CacheWarmupController.php line 120 

Cheers Ingo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @IngoMueller, thanks for reporting this issue. I resolved it with #74 and will publish a new release soon.

**Comment by IngoMueller** [comment]
Hi @eliashaeussler, thanks for taking care of this issue.

**Comment by eliashaeussler** [comment]
@IngoMueller FYI: I released a new version [`0.3.20`](https://github.com/eliashaeussler/typo3-warming/releases/tag/0.3.20).
