### ISSUE TITLE
[BUG] Disabled languages are included

### ISSUE THREAD

**Issue by Tim-Obert** [eliashaeussler/typo3-warming#98]
### TYPO3 version

10.4.32

### PHP version

7.4.29

### Extension version

0.4.0

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Debian 11

### Current behavior

A disabled language is still included in the action that fetches the available sites.
This leads to an infinite loop in the backend (or really long loading time).

### Expected behavior

Disabled Languages should not be included in the fetchSitesAction. 

### Steps to reproduce

1. Have a normal Site configured
2. configure a language in that site which is disabled
3. open backend

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@Tim-Obert Thanks!

**Comment by Tim-Obert** [comment]
Thank you for the quick merge 😄
